language: csharp
solution: ConfigDownloader.sln
before_deploy: 
  - sudo apt-get -y install dos2unix zip
  - dos2unix travisbefore.sh
  - bash travisbefore.sh
deploy:
  provider: releases
  api_key:
    secure: iQw+e+gX/Dc/u9uzjMacehy7A/ZUJavl4xlil/iYbZe9eaVs2PqDDPzfgwxnGDaevDoCGY5OXAAZqZJcywyynDLH337/KoMr1UHNKEp/yhBm42D5tq/dej9PUTxPZsP16xqbEJkgGn9WP6QxLVjeZmun85ndOTNS9AMmHyFlp+GI3XqqC7XsHBMkz1WVzM48tX07TH8Mmrc+HTayaN7jNeKpv29IJp7Zs1zSLWUVD5pzlGfshv6VGwXT4jMVPJ9VDohZ3NEVv1danhLG7AjICKCOxg7foQS3RLbI3T5n1WTPVAxvLjC1lqM6OrfX8oeZW/iXe08MGISzVKqy8VMLiU5uNxZMnPyezbcC6FSwTyhtOdOVZ95C1J45ol24mjrG8gUfdweutZuNsEQ94vLgr3GudmFF0TvuE4utyLcv8zEzcvnDn5Qd1t/EIFWc9jQfaBBx6xuC9CWL6+AV7Y/nc6cRQUf0c7k+qXqsfY/6m3GKmuGBgNK/eQbNYBHsmXIKrY1/ZeqF73I25nnX1BwRRU6mD3ur8dv0jYezuq0cOfyIqUpceRvRl0hJFBa6sAUdOKxZLMIIEtlUyh6/zlHhSo6GlYnQHoHcqZEDwTO7zmCdj6mm//ot06AjpzPhKSlAVGBm3ACtuw+WWR7o+Dl/Pj2vS1iN+ya+WpNqGyys9aY=
  file: bin/Debug/SCConfigDownloader.zip
  skip_cleanup: true
  prerelease: true
  on:
    tags: true
